# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13072d03120e1d4799bf85be4b953533c4b2bd9babf1b7cc4b9bb972e6beb28caacdfd925911a71a92e9a8a7c1c3d9085e006a96c224edff96f6706f9186f30a

test:
  secret_key_base: 9b815717872c282b9b807a78b0483126a9c75b36edae12ba94757a7d01127c1ee2424020f9c4b5ec8f6730b246ef613586f114d3d347e5a4c9a727dbca9fb05f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
